### ISSUE TITLE
Update Readme.md with proper screenshots and setup details

### ISSUE THREAD

**Issue by abhayy143** [abhayy143/bootcamp_website#4]
The readme.md file present in the repo would be much more clear & encouraging if one could update it with proper screenshots & helping out newbies on GitHub to setup the site and adding their content :P

**Comment by Rishav1707** [comment]
Shall I work on this issue? @abhayy143

**Comment by abhayy143** [comment]
Go on, I've assigned you the issue @Rishav1707
